export const FETCH_DATA_REQUEST = "FETCH_DATA_REQUEST";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_FAILURE = "FETCH_DATA_FAILURE";
export const OPEN_WORKOUT_MODAL = "OPEN_WORKOUT_MODAL";
export const CLOSE_WORKOUT_MODAL = "CLOSE_WORKOUT_MODAL";
